### PR TITLE
Add Modoboa plugins for rc-vacation

### PR DESCRIPTION
**Pull request by stefaweb**
Look at https://modoboa.org/

Add plugins to communicate with Modoboa mail system using Modoboa API.
Modified vacation.php to manage PLUGIN_ERROR_DATE.
Added language message for fr_FR.php et en_US.php.
Corrected wrong linefeed in de_DE.php.
Clean-up in various files.

### CODE REVIEW

**Comment by bhuisgen** [comment]
New plugin :)

**Comment by stefaweb** [comment]
Hello @bhuisgen!

Have you tried to publish the rc-vacation plugin in master RoundCube project?

Or at least, in https://plugins.roundcube.net/.

In the curent RoundCube, they don't have a vacation plugins.

**Comment by bhuisgen** [comment]
@stefaweb it's done! https://plugins.roundcube.net/packages/bhuisgen/rc-vacation

**Comment by stefaweb** [comment]
Great!

**Pull request merged**
